name: yal-client-ci

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "dist/client/**"
      - ".github/workflows/yal-client-ci.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up docker build
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push proxy code
        uses: docker/build-push-action@v4
        with:
          context: ./dist/client
          file: ./dist/client/Dockerfile
          push: true
          tags: terinss/yal-nginx:latest